# This is used with the label workflow which
# will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# For more information, see:
# https://github.com/actions/labeler
#
# ├── ./src/courses
# │   ├── ./courses/advanced
# │   ├── ./courses/beginner
# │   ├── ./courses/delta
# │   ├── ./courses/guidance
# │   └── ./courses/profile-dev-test
# │   └── ./courses/user

'advanced':
  - changed-files:
    - any-glob-to-any-file: ['src/courses/advanced/**/*']

'beginner':
  - changed-files:
    - any-glob-to-any-file: ['src/courses/beginner/**/*']

'delta':
  - changed-files:
    - any-glob-to-any-file: ['src/courses/delta/**/*']

'guidance':
  - changed-files:
    - any-glob-to-any-file: ['src/courses/guidance/**/*']

'profile-dev-test':
- changed-files:
  - any-glob-to-any-file: ['src/courses/profile-dev-test/**/*']

'user':
- changed-files:
  - any-glob-to-any-file: ['src/courses/user/**/*']

'courses':
  - changed-files:
    - any-glob-to-any-file: ['src/courses/**/*']

